import { Inter } from "next/font/google";
import { ApolloProvider } from "@apollo/client";
import { client } from "../lib/apolloClient";
import "./globals.css";
import UserContextProviders from "@/context/userContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: React.ReactNode;
}

export default function RootLayout({ children }: Readonly<RootLayoutProps>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ClientLayout>{children}</ClientLayout>
      </body>
    </html>
  );
}

// Ensure ClientLayout is wrapped for client-specific functionality
function ClientLayout({ children }: { children: React.ReactNode }) {
  return (
    <ApolloProvider client={client}>
      <UserContextProviders>{children}</UserContextProviders>
    </ApolloProvider>
  );
}
